#!/usr/bin/env bash
# =============================================================================
# initialize.sh — runs on HOST before the devcontainer starts
# =============================================================================
# Called by devcontainer.json's `initializeCommand`. Does two things:
#
#   1. Auto-generates .devcontainer/.env on first run with sensible defaults
#      AND randomly-generated GUI/VNC passwords. User never needs to set them
#      manually. If .env already exists, this script does NOT overwrite —
#      your edits and rotated passwords are safe.
#
#   2. Prints the GUI credentials so you can sign in right after the container
#      starts. Read them back later with `cat .devcontainer/.env`.
#
# Everything is defaulted. The container starts cleanly even without .env —
# docker-compose.yml has fallback values for every variable.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$DEVC_DIR/.env"

# Project name = parent directory of .devcontainer/
PROJECT_NAME="$(basename "$(cd "$DEVC_DIR/.." && pwd)")"

# Generate a URL-safe random secret. Falls back to /dev/urandom if openssl
# missing (it's not on every host).
gen_secret() {
    local len="${1:-16}"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 "$((len * 3 / 4 + 1))" | tr -d '/+=\n' | head -c "$len"
    else
        LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$len"
    fi
}

if [ ! -f "$ENV_FILE" ]; then
    GUI_USER="admin"
    GUI_PASS="$(gen_secret 16)"
    VNC_PASS="$(gen_secret 12)"

    umask 077
    cat > "$ENV_FILE" <<EOF
# Auto-generated by .devcontainer/scripts/initialize.sh on first run.
# Edit if you want to rotate passwords or override defaults. This file is
# gitignored by default — do NOT commit it.

PROJECT_NAME=$PROJECT_NAME

# GUI (noVNC) credentials — used to sign in at http://localhost:5800
WEB_AUTHENTICATION_USERNAME=$GUI_USER
WEB_AUTHENTICATION_PASSWORD=$GUI_PASS

# VNC tunnel password (rarely needed; only if you connect via a native VNC client)
VNC_PASSWORD=$VNC_PASS

# Uncomment to override defaults (see docker-compose.yml for the full list)
# BACKEND_PORT=8091
# BIND_IP=127.0.0.1
# DFAI_ENABLED=1
# DFAI_PORT=1080
# VNC_PORT=5800

# ── Container-start auto-update (post-start.sh) ─────────────────────────
# Every container start runs `npm install -g @anthropic-ai/claude-code@latest
# ruflo@latest` (60s timeout, non-fatal on failure). To freeze, set either:
# SKIP_AUTO_UPDATE=1
# CLAUDE_CODE_VERSION=1.x.y
# RUFLO_VERSION=0.x.y
EOF
    chmod 600 "$ENV_FILE"

    cat <<EOF

╭──────────────────────────────────────────────────────────────╮
│  Generated .devcontainer/.env for project '$PROJECT_NAME'
│
│  GUI URL:      http://localhost:5800
│  GUI user:     $GUI_USER
│  GUI password: $GUI_PASS
│  VNC password: $VNC_PASS
│
│  Read these back any time with:
│      cat .devcontainer/.env
│
│  This file is gitignored. Do not commit it.
╰──────────────────────────────────────────────────────────────╯

EOF
fi

# Ensure host-side dirs that the compose bind-mounts expect actually exist —
# Docker would create them as root-owned otherwise, breaking permissions.
mkdir -p "$HOME/.myclaude/$PROJECT_NAME/share" \
         "$HOME/.myclaude/$PROJECT_NAME/claude-flow" \
         "$HOME/.myclaude/$PROJECT_NAME/config-claude" \
         "$HOME/.myclaude-gui/$PROJECT_NAME" \
         "$HOME/.ssh/devcontainer" \
         "$HOME/.myclaude/_shared/npm-global" \
         "$HOME/.myclaude/_shared/npm-cache" \
         "$HOME/.myclaude/_shared/pnpm-store" \
         "$HOME/.myclaude/_shared/go" \
         "$HOME/.myclaude/_shared/cache"
touch    "$HOME/.ssh/devcontainer/known_hosts"
