"""slice5 recommendation model

Revision ID: 0dae9d9079db
Revises: a7d25124924f
Create Date: 2026-05-29 20:24:24.228803
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0dae9d9079db'
down_revision: str | None = 'a7d25124924f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('requires_human_confirmation', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_decision', sa.Enum('ACCEPTED', 'REJECTED', 'DEFERRED', name='recodecision'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_user', ['user_id'], unique=False)
        batch_op.create_index('ix_recommendation_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendation_user_created')
        batch_op.drop_index('ix_recommendation_user')

    op.drop_table('recommendation')
    # ### end Alembic commands ###
