"""slice3 competency model

Revision ID: 381dc7674cdd
Revises: aa69acb06426
Create Date: 2026-05-29 17:26:18.935249
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '381dc7674cdd'
down_revision: str | None = 'aa69acb06426'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('area', sa.Enum('A_PERSONAL', 'B_EXPLORATION', 'C_BUILDING', name='competencyarea'), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('dieu5_codes', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('competency', schema=None) as batch_op:
        batch_op.create_index('ix_competency_area', ['area'], unique=False)

    op.create_table('indicator',
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('depth', sa.Enum('K', 'A', 'R', name='depth'), nullable=False),
    sa.Column('statement_vi', sa.Text(), nullable=False),
    sa.Column('dieu5_code', sa.String(length=8), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_competency_depth', ['competency_id', 'depth'], unique=False)

    op.create_table('learner_domain_phase',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('area', sa.Enum('A_PERSONAL', 'B_EXPLORATION', 'C_BUILDING', name='competencyarea'), nullable=False),
    sa.Column('dev_phase', sa.Enum('AWARENESS', 'EXPLORATION', 'PLANNING', name='devphase'), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learner_domain_phase', schema=None) as batch_op:
        batch_op.create_index('ix_learner_domain_phase_user_area', ['user_id', 'area'], unique=False)

    op.create_table('learner_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('depth_achieved', sa.Enum('K', 'A', 'R', name='depth'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learner_progress', schema=None) as batch_op:
        batch_op.create_index('ix_learner_progress_user_competency', ['user_id', 'competency_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learner_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_learner_progress_user_competency')

    op.drop_table('learner_progress')
    with op.batch_alter_table('learner_domain_phase', schema=None) as batch_op:
        batch_op.drop_index('ix_learner_domain_phase_user_area')

    op.drop_table('learner_domain_phase')
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_competency_depth')

    op.drop_table('indicator')
    with op.batch_alter_table('competency', schema=None) as batch_op:
        batch_op.drop_index('ix_competency_area')

    op.drop_table('competency')
    # ### end Alembic commands ###
