"""slice7 content_editor flag, content lineage, support_request

Revision ID: 5fecd1fe010a
Revises: 845207d77247
Create Date: 2026-05-29 23:41:11.044075
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5fecd1fe010a'
down_revision: str | None = '845207d77247'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_request',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('counselor_id', sa.String(length=36), nullable=True),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='counselingtier'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'CLOSED', name='supportrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.create_index('ix_support_request_counselor', ['counselor_id'], unique=False)
        batch_op.create_index('ix_support_request_student', ['student_id'], unique=False)

    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lineage_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_content_item_lineage', ['lineage_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # server_default false so existing rows backfill to "not a content
        # editor"; the column is NOT NULL going forward.
        batch_op.add_column(
            sa.Column(
                'is_content_editor',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_content_editor')

    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.drop_index('ix_content_item_lineage')
        batch_op.drop_column('lineage_id')

    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.drop_index('ix_support_request_student')
        batch_op.drop_index('ix_support_request_counselor')

    op.drop_table('support_request')
    # ### end Alembic commands ###
