"""slice6 school channel and counseling

Revision ID: 845207d77247
Revises: 0dae9d9079db
Create Date: 2026-05-29 22:07:40.358160
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '845207d77247'
down_revision: str | None = '0dae9d9079db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counseling_session',
    sa.Column('counselor_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='counselingtier'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counseling_session', schema=None) as batch_op:
        batch_op.create_index('ix_counseling_session_counselor', ['counselor_id'], unique=False)
        batch_op.create_index('ix_counseling_session_student', ['student_id'], unique=False)

    op.create_table('school_class',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.create_index('ix_school_class_school', ['school_id'], unique=False)

    op.create_table('school_membership',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'COUNSELOR', 'SCHOOL_ADMIN', name='schoolrole'), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', 'role', name='uq_membership_user_school_role')
    )
    with op.batch_alter_table('school_membership', schema=None) as batch_op:
        batch_op.create_index('ix_school_membership_school_role', ['school_id', 'role'], unique=False)
        batch_op.create_index('ix_school_membership_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_membership', schema=None) as batch_op:
        batch_op.drop_index('ix_school_membership_user')
        batch_op.drop_index('ix_school_membership_school_role')

    op.drop_table('school_membership')
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.drop_index('ix_school_class_school')

    op.drop_table('school_class')
    with op.batch_alter_table('counseling_session', schema=None) as batch_op:
        batch_op.drop_index('ix_counseling_session_student')
        batch_op.drop_index('ix_counseling_session_counselor')

    op.drop_table('counseling_session')
    op.drop_table('school')
    # ### end Alembic commands ###
