"""slice1 auth and guardian consent schema

Revision ID: a09799b3413a
Revises: 
Create Date: 2026-05-29 11:57:05.375767
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a09799b3413a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('is_sensitive_access', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age_band', sa.Enum('UNDER_16', 'BAND_16_17', 'ADULT', name='ageband'), nullable=False),
    sa.Column('user_type', sa.Enum('STUDENT', 'WORKING', name='usertype'), nullable=False),
    sa.Column('school_level', sa.Enum('PRIMARY', 'LOWER_SECONDARY', 'UPPER_SECONDARY', 'TERTIARY', 'NONE', name='schoollevel'), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'PENDING_GUARDIAN_CONSENT', 'SUSPENDED', 'DELETED', name='accountstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_age_status', ['age_band', 'account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('guardian_link',
    sa.Column('child_user_id', sa.String(length=36), nullable=False),
    sa.Column('guardian_user_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('verification_method', sa.Enum('EMAIL', 'VNEID', 'MANUAL', name='verificationmethod'), nullable=False),
    sa.Column('assurance_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='assurancelevel'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardian_link', schema=None) as batch_op:
        batch_op.create_index('ix_guardian_link_child', ['child_user_id'], unique=False)
        batch_op.create_index('ix_guardian_link_guardian', ['guardian_user_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('guardian_consent',
    sa.Column('child_user_id', sa.String(length=36), nullable=False),
    sa.Column('guardian_link_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_link_id'], ['guardian_link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardian_consent', schema=None) as batch_op:
        batch_op.create_index('ix_guardian_consent_child_status', ['child_user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardian_consent', schema=None) as batch_op:
        batch_op.drop_index('ix_guardian_consent_child_status')

    op.drop_table('guardian_consent')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('guardian_link', schema=None) as batch_op:
        batch_op.drop_index('ix_guardian_link_guardian')
        batch_op.drop_index('ix_guardian_link_child')

    op.drop_table('guardian_link')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index('ix_user_age_status')

    op.drop_table('user')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
