"""slice4 careers model

Revision ID: a7d25124924f
Revises: 381dc7674cdd
Create Date: 2026-05-29 19:16:44.898819
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a7d25124924f'
down_revision: str | None = '381dc7674cdd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profile',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('riasec_codes', sa.String(length=32), nullable=False),
    sa.Column('required_competencies', sa.String(length=128), nullable=False),
    sa.Column('training_level', sa.Enum('SECONDARY', 'VOCATIONAL', 'COLLEGE', 'UNIVERSITY', 'POSTGRADUATE', name='traininglevel'), nullable=False),
    sa.Column('training_paths', sa.Text(), nullable=False),
    sa.Column('labor_market_outlook', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dieu5_code', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('career_profile', schema=None) as batch_op:
        batch_op.create_index('ix_career_profile_field', ['field'], unique=False)
        batch_op.create_index('ix_career_profile_training_level', ['training_level'], unique=False)

    op.create_table('content_item',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dieu5_code', sa.String(length=8), nullable=False),
    sa.Column('competency_code', sa.String(length=16), nullable=False),
    sa.Column('depth', sa.Enum('K', 'A', 'R', name='depth'), nullable=True),
    sa.Column('dev_phase', sa.Enum('AWARENESS', 'EXPLORATION', 'PLANNING', name='devphase'), nullable=True),
    sa.Column('school_level', sa.Enum('PRIMARY', 'LOWER_SECONDARY', 'UPPER_SECONDARY', 'TERTIARY', 'NONE', name='schoollevel'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.create_index('ix_content_item_filters', ['dieu5_code', 'competency_code', 'dev_phase', 'school_level'], unique=False)
        batch_op.create_index('ix_content_item_status', ['status'], unique=False)

    op.create_table('pathway',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ACADEMIC', 'VOCATIONAL_SECONDARY', 'GDNN', 'LABOR', name='pathwaytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pathway', schema=None) as batch_op:
        batch_op.create_index('ix_pathway_type', ['type'], unique=False)

    op.create_table('career_pathway',
    sa.Column('career_id', sa.String(length=36), nullable=False),
    sa.Column('pathway_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathway.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_pathway', schema=None) as batch_op:
        batch_op.create_index('ix_career_pathway_career_pathway', ['career_id', 'pathway_id'], unique=True)
        batch_op.create_index('ix_career_pathway_pathway', ['pathway_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_pathway', schema=None) as batch_op:
        batch_op.drop_index('ix_career_pathway_pathway')
        batch_op.drop_index('ix_career_pathway_career_pathway')

    op.drop_table('career_pathway')
    with op.batch_alter_table('pathway', schema=None) as batch_op:
        batch_op.drop_index('ix_pathway_type')

    op.drop_table('pathway')
    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.drop_index('ix_content_item_status')
        batch_op.drop_index('ix_content_item_filters')

    op.drop_table('content_item')
    with op.batch_alter_table('career_profile', schema=None) as batch_op:
        batch_op.drop_index('ix_career_profile_training_level')
        batch_op.drop_index('ix_career_profile_field')

    op.drop_table('career_profile')
    # ### end Alembic commands ###
