"""slice2 assessments schema

Revision ID: aa69acb06426
Revises: a09799b3413a
Create Date: 2026-05-29 13:26:42.158884
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aa69acb06426'
down_revision: str | None = 'a09799b3413a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_instrument',
    sa.Column('type', sa.Enum('RIASEC', 'VIPS', 'MBTI', name='instrumenttype'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_instrument', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_instrument_type_active', ['type', 'is_active'], unique=False)

    op.create_table('assessment_item',
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=32), nullable=False),
    sa.Column('competency_code', sa.String(length=16), nullable=False),
    sa.Column('dieu5_code', sa.String(length=8), nullable=False),
    sa.Column('prompt_vi', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['assessment_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_item', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_item_instrument', ['instrument_id'], unique=False)

    op.create_table('assessment_result',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('result_payload', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['assessment_instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_result_user_instrument_version', ['user_id', 'instrument_id', 'version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_result_user_instrument_version')

    op.drop_table('assessment_result')
    with op.batch_alter_table('assessment_item', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_item_instrument')

    op.drop_table('assessment_item')
    with op.batch_alter_table('assessment_instrument', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_instrument_type_active')

    op.drop_table('assessment_instrument')
    # ### end Alembic commands ###
